[global]
    frame_color = "#afc6ff"
    separator_color = "#44464f"

[urgency_low]
    background = "#1e1f25"
    foreground = "#e2e2e9"

[urgency_normal]
    background = "#282a2f"
    foreground = "#e2e2e9"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
