[global]
    frame_color = "#90cef4"
    separator_color = "#41484d"

[urgency_low]
    background = "#1c2023"
    foreground = "#dfe3e7"

[urgency_normal]
    background = "#262b2e"
    foreground = "#dfe3e7"

[urgency_critical]
    background = "#93000a"
    foreground = "#ffdad6"
    frame_color = "#ffb4ab"
