foreground #dfe3e7
background #0f1417
selection_foreground #00344a
selection_background #90cef4
cursor #dfe3e7

# Normal colors
color0 #0f1417
color1 #ffb4ab
color2 #90cef4
color3 #cbc1e9
color4 #b6c9d7
color5 #004c69
color6 #374955
color7 #dfe3e7
