foreground #e2e2e9
background #121318
selection_foreground #142f60
selection_background #afc6ff
cursor #e2e2e9

# Normal colors
color0 #121318
color1 #ffb4ab
color2 #afc6ff
color3 #dfbbde
color4 #bfc6dc
color5 #2d4578
color6 #404659
color7 #e2e2e9
